[package]
name = "zklend_market"
version = "0.1.0"
edition = "2024_07"
license = "Apache-2.0"

[dependencies]
starknet = "2.8.0"

[dev-dependencies]
snforge_std = "0.61.0"

[[target.starknet-contract]]
sierra = true
casm = false
